### ISSUE TITLE
Error: Cannot access protected property FieldCollectionItemEntity::$langcode

### ISSUE THREAD

**Issue by MrToniOni** [BWPanda/pdf_to_image#9]
Hello folks,

I’m a bit unexperienced with this – please be nice. :-)

Saving my node I get the error message "Cannot access protected property FieldCollectionItemEntity::$langcode"

In the protocol it says:
`Error: Cannot access protected property FieldCollectionItemEntity::$langcode in pdf_to_image_entity_presave() (Line 181 of /………/modules/pdf_to_image/pdf_to_image.module).`

I googled some days to find a comparable error but did not identify one as the same.

The requirements for the module are met — I double checked that.

I’d be glad if anyone can help me on this. Feel free to DM.

**Comment by argiepiano** [comment]
Hi @MrToniOni. Thanks for reporting this issue. 

I see you are using Field Collection in your site. There is no official release of Field Collection, so the problem may lie there (since there are likely some bugs in Field Collection), rather than on this module. Or, very likely, on a combination of both modules. 

To debug, you may want to fully remove your field collections from your nodes, and instead work with regular fields. Most likely, this error will not show up then.

Having taken a quick look at the offending line here, and at the way Field Collection defines the field collection entity class, I see that Field Collection uses `protected $langcode;`, which is very unusual. Backdrop's entities do not use the `protected` visibility for langcode. Rather, B's core entities define it as public (see `Node` for example).

So, another quick test for you would be to edit the file `field_collection/field_collection.entity.inc` and change `protected $langcode;` to `public $langcode;`.  BUT, of course, this will not assure there wouldn't be other problems down the line.  

You may want to report here after trying the above.

**Comment by argiepiano** [comment]
In the meantime I have also opened an [issue](https://github.com/backdrop-contrib/field_collection/issues/15) in field_collection, but since there is no official release of that module, it may take a while to get fixed.

**Comment by a8w4** [comment]
Thx @argiepiano for pitching in!
